with-expecter: true
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: mocks
dir: "./mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/tsamsiyu/themelio/api/internal/repository:
    interfaces:
      ResourceRepository:
      ClientWrapper:
      ResourceStore:
      SchemaRepository:
  github.com/tsamsiyu/themelio/api/internal/service/shared:
    interfaces:
      SchemaService:
